Repository openimsdk/openim-sdk-cpp, pull requests merged in 2024-07, with the labels that each got.

#16 feat: update sdk core version to 3.8.0
  go/constant.go
  go/export.go
  go/go.mod
  go/go.sum
Labels: size/L

#17 fix: token invalid cb.
  go/go.mod
  go/go.sum
Labels: size/S

#18 feat: add functions of get users in group.
  go/export.go
  go/go.mod
  go/go.sum
Labels: size/M

#19 feat: dump sdk-core version to v3.8.0-rc14
  go/export.go
  go/go.mod
  go/go.sum
Labels: size/M

#20 dump sdk-core version to v3.8.0-rc.15.
  go/go.mod
  go/go.sum
Labels: size/XS

#21 dump sdk core vertion to v3.8.0-rc.16.
  go/go.mod
  go/go.sum
Labels: size/S

#22 dump sdk core version to v3.8.0-rc.17
  go/constant.go
  go/export.go
  go/go.mod
  go/go.sum
Labels: size/M

#23 dump sdk version to v3.8.0-rc.18.
  go/go.mod
  go/go.sum
Labels: size/XS

#24 feat: add functions about logs upload and app badge.
  go/export.go
Labels: size/M

#25 dump sdk version to v3.8.0-rc.19
  go/go.mod
  go/go.sum
Labels: size/XS
