Repository openimsdk/openim-sdk-cpp, pull requests merged in 2024-11, with the labels that each got.

#61 build: update sdk version to v3.8.2-alpha.4.
  go/go.mod
  go/go.sum
Labels: size/XS

#58 untiy change some function
  README.md
  api.go
  constant.go
  export.go
  gen_ios_dylib.sh
  gen_linux_so.sh
  gen_mac_dylib.sh
  gen_openharmony_so.bat
  gen_win_dll.bat
  listener.go
Labels: size/L

#63 build: update sdk version to v3.8.2-beta.2
  go/go.mod
  go/go.sum
  go/protocol.go
Labels: size/S

#65 build: update sdk version to v3.8.2
  go/go.mod
  go/go.sum
Labels: size/XS
