Repository openimsdk/openim-sdk-cpp, pull requests merged in 2024-10, with the labels that each got.

#53 feat: auto build win32 platform dll with ci
  .github/workflows/auto-build-electron.yml
  magefile.go
Labels: size/M

#54 feat: add change_input_states and get_input_states, and add login and logout alternative func.
  bootstrap_install_mage.sh
  go/export.go
Labels: size/M

#51 Unity update sdk to 3.8.1
  .github/.codecov.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-invite.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gosec.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/issue-robot.yml
  .github/workflows/link-pr.yml
  .github/workflows/opencommit.yml
  .github/workflows/project-progress.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .gitignore
  CMakeLists.txt
  README.md
  examples/CMakeLists.txt
  examples/main.cpp
  export.go
  gen/gen_win_dll.bat
  gen/go.mod
  gen/go.sum
  gen_android_so.bat
  gen_ios_dylib.sh
  gen_linux_so.sh
  gen_mac_dylib.sh
  gen_win_dll.bat
  go.mod
  go.sum
  include/imsdk.h
  message.go
  protocol.go
  scripts/githooks/commit-msg
  scripts/githooks/commit-msg.sh
  scripts/githooks/pre-commit
  scripts/githooks/pre-commit.sh
  scripts/githooks/pre-push
  scripts/githooks/pre-push.sh
  src/imsdk.cpp
  src/json.hpp
Labels: size/XXL

#55 Modify export method
  api.go
  constant.go
  data.go
  export.go
  gen_android_so.bat
  gen_ios_dylib.sh
  gen_linux_so.sh
  gen_mac_dylib.sh
  gen_win_dll.bat
  go.mod
  go.sum
  listener.go
Labels: size/XXL

#57 fix: remove unused space.
  go/export.go
Labels: size/XS

#60 build: update sdk version to v3.8.2-alpha.2
  go/go.mod
  go/go.sum
Labels: size/M
