Repository openimsdk/openim-sdk-cpp, pull requests merged in 2024-09, with the labels that each got.

#35 update sdk version to v3.8.1-rc.10
  go/go.mod
  go/go.sum
Labels: size/S

#36 update sdk version to v3.8.1-rc.11
  go/go.mod
  go/go.sum
Labels: size/S

#37 update sdk version to v3.8.1-rc.12
  go/go.mod
  go/go.sum
Labels: size/XS

#38 update sdk version to v3.8.1-rc.13
  go/go.mod
  go/go.sum
Labels: size/XS

#39 update sdk version to v3.8.1-rc.14
  go/go.mod
  go/go.sum
Labels: size/XS

#40 update sdk version to v3.8.1-rc.15
  go/go.mod
  go/go.sum
Labels: size/XS

#41 update sdk version to v3.8.1-rc.16
  go/go.mod
  go/go.sum
Labels: size/S

#42 update sdk version to v3.8.1-rc.19
  go/export.go
  go/go.mod
  go/go.sum
Labels: size/L

#43 upgrade sdk version to v3.8.1-rc.21.
  go/export.go
  go/go.mod
  go/go.sum
Labels: size/S

#45 chore: update interface name.
  go/export.go
Labels: size/XS

#47 fix: build with target arch
  .github/workflows/auto-build-electron.yml
  magefile.go
Labels: size/M

#48 update sdk version to v3.8.1-rc.22
  go/go.mod
  go/go.sum
Labels: size/XS

#49 feat: update sdk version to 3.8.1
  go/go.mod
  go/go.sum
Labels: size/XS

#50 update build ios script
  README.md
  gen/gen_android_so.bat
  gen/gen_ios_dylib.sh
  gen/gen_linux_so.sh
  gen/gen_mac_dylib.sh
  gen/gen_win_dll.bat
  include/imsdk.h
  src/imsdk.cpp
Labels: size/M
