Repository openimsdk/openim-sdk-cpp, pull requests merged in 2024-05, with the labels that each got.

#10 Feat: update sdk to v3.5.1 and refactor project structure.
  .gitignore
  bootstrap_install_mage.bat
  bootstrap_install_mage.sh
  c/CMakeLists.txt
  c/include/README.md
  c/src/test.c
  c_cpp_wrapper/build_test.bat
  c_cpp_wrapper/event_listener/listener.go
  c_cpp_wrapper/gen_android_so.bat
  c_cpp_wrapper/go.mod
  c_cpp_wrapper/go.sum
  cpp/include/README.md
  cpp/src/test.cc
  go/constant.go
  go/export.go
  go/go.sum
  go/protocol.go
  go/tools.go
  magefile.go
  scripts/build_dll.bat
  scripts/build_run_test.bat
  scripts/build_so.sh
  scripts/build_test.bat
  scripts/gen_android_so.bat
  scripts/gen_ios_dylib.sh
  scripts/githooks/commit-msg
  scripts/githooks/commit-msg.sh
  scripts/githooks/pre-commit
  scripts/githooks/pre-commit.sh
  scripts/githooks/pre-push
  scripts/githooks/pre-push.sh
  scripts/openimsdk.h
  scripts/openimsdkcc.cc
  scripts/openimsdkcc.h
  scripts/run_test.sh
  scripts/wrapp_cpp_function.inc
  shared/android/README.md
  shared/ios/README.md
  shared/linux/README.md
  shared/windows/README.md
Labels: size/XXL

#11 refactor: change cpp structure.
  c/src/test.c
  cpp/include/libopenimsdkcc.h
  cpp/include/wrapp_cpp_function.inc
  cpp/src/libopenimsdkcc.cc
  go/export.go
Labels: size/M

#12 fix: convert c char to Go string.
  go/export.go
  magefile.go
Labels: size/XS

#13 fix: gitignore remove *.mod.
  .gitignore
  go/go.mod
Labels: size/M

#14 fix: sdk add function for upload file.
  go/constant.go
  go/export.go
  go/tools.go
Labels: size/L

#15 ci: auto build electron assets
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-build-electron.yml
  .github/workflows/auto-invite.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gosec.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/issue-robot.yml
  .github/workflows/link-pr.yml
  .github/workflows/opencommit.yml
  .github/workflows/project-progress.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
Labels: size/XL
